language: node_js

node_js:
- 12

before_install:
- npx version-from-git --travis
- export NPM_PACKAGE_VERSION=`jq -r .version package.json`

install:
- npm ci
- npm run prepublishOnly

before_deploy:
- npm pack
- cp botframework-directlinejs-speech-$NPM_PACKAGE_VERSION.tgz botframework-directlinejs-speech.tgz
- cp dist/directlinespeech.js dist/directlinespeech-$NPM_PACKAGE_VERSION.js
- cp public/index.html dist
- export TRAVIS_TAG=dev
- git tag -f $TRAVIS_TAG

deploy:
- provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
  skip_cleanup: true

- provider: releases
  api_key: $GITHUB_TOKEN
  body: "This build will be updated on every push. Please do not use it for production use."
  file:
  - dist/directlinespeech*.js
  - botframework-directlinejs-speech*.tgz
  file_glob: true
  name: "Continuous integration build"
  on:
    branch: master
  overwrite: true
  prerelease: true
  skip_cleanup: true
